# Generated by Django 4.2.9 on 2024-01-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_services', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='FuelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('currency', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ImageURLs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urls', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Source2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_price', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='azs.fuelprice')),
            ],
        ),
        migrations.CreateModel(
            name='Source1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.FloatField()),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=256)),
                ('additional_services', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='azs.additionalservices')),
                ('image_urls', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='azs.imageurls')),
            ],
        ),
    ]
