# Generated by Django 4.2.9 on 2024-01-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurls',
            name='urls',
            field=models.URLField(max_length=300),
        ),
    ]
