# Generated by Django 4.2.9 on 2024-01-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0002_alter_imageurls_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageurls',
            name='urls',
            field=models.URLField(),
        ),
    ]
