# Generated by Django 4.2.9 on 2024-01-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0004_rename_additional_services_additionalservices_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source1',
            name='coordinates',
            field=models.CharField(max_length=32),
        ),
        migrations.RemoveField(
            model_name='source2',
            name='fuel_price',
        ),
        migrations.AddField(
            model_name='source2',
            name='fuel_price',
            field=models.ManyToManyField(to='azs.fuelprice'),
        ),
    ]
