# Generated by Django 4.2.9 on 2024-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azs', '0005_alter_source1_coordinates_remove_source2_fuel_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source1',
            name='additional_services',
        ),
        migrations.RemoveField(
            model_name='source1',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='source1',
            name='additional_services',
            field=models.ManyToManyField(to='azs.additionalservices'),
        ),
        migrations.AddField(
            model_name='source1',
            name='image_urls',
            field=models.ManyToManyField(to='azs.imageurls'),
        ),
    ]
